authentication/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from .views import account_activation_sent,account_invite,invite_accept
from authentication import views as core

app_name = 'authentication'

urlpatterns = [

    url(r'^login/$', core.LoginView.as_view(), name='login'),
    url(r'^signup/$', core.RegisterView.as_view(), name='signup'),
    url(r'^invite/$', account_invite, name='invite'),
    url(r'^invite/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/accept$',
        invite_accept,
        name='invite-accept'),
    url(r'^logout/$', core.LogoutView.as_view(), name='logout'),
    url(r'^profile/$', core.AccountSettingsView.as_view(), name='settings'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(**{
            'template_name': 'authentication/registration/password_reset_form.html',
            'from_email': 'salesleadgen@mohit-development.website',
            'email_template_name': 'authentication/registration/password_reset_email.html',
            'subject_template_name': 'authentication/registration/password_reset_subject.txt',
            'success_url':reverse_lazy('authentication:password_reset_done')
        }),
        name='password_reset'
        ),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
            **{'template_name': 'authentication/registration/password_reset_done.html'}),
        name='password_reset_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core.activate, name='activate'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(**{
            'success_url': reverse_lazy('authentication:password_reset_complete'),
            'template_name': 'authentication/registration/password_reset_confirm.html'
        }),
        name='password_reset_confirm'
        ),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(**{
            'template_name': 'authentication/registration/password_reset_complete.html'
        }),
        name='password_reset_complete'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),

]

core/urls.py
from django.conf.urls import url,include
from core.views import (
    dashboard,

)

app_name = 'core'

urlpatterns = [

    url(r'^$', dashboard, name='dashboard'),

    # url(r'^ta', core_ta, name='ta'),

    # url(r'^sample_model/', include(([
    #     url(r'^create$', search_create,name='create'),
    #
    #     url(r'^(?P<sample_model_pk>\d+)/', include(([
    #         url(r'^$', search_summary, name='summary'),
    #         url(r'^track_node$', search_track_node, name='track_node'),
    #
    #     ],'search'))),
    # ],'searches'))),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.urls import path
from django.conf import settings

urlpatterns = [
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar

    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm,UsernameField
from django.contrib.auth import get_user_model

from django.utils.translation import gettext, gettext_lazy as _


class SignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'first_name','last_name', 'password1', 'password2',)

    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification. (also to catch typos)"),
    )

    first_name = forms.CharField(required=False)


    # def _post_clean(self):
    #     super()._post_clean()
    #     # Validate the email hasn't been used by an account yet
    #     #  after self.instance is updated with form data
    #     # by super().
    #     email = self.cleaned_data.get("email")
    #     if Email.objects.filter().exists():
    #         self.add_error('email', error)


class AccountSettingsForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'username', 'first_name','last_name','company', 'password1', 'password2',)

    first_name = forms.CharField(required=False)



class SignInForm(AuthenticationForm):

    username = UsernameField(
        max_length=254,
        label='Username or Email' # the form is extended to edit this label
    )


class AccountInviteForm(forms.Form):
    email = forms.EmailField(help_text='User Email',required=True)

authentication/views.py
import logging

from django.contrib.auth import REDIRECT_FIELD_NAME, login as auth_login, logout as auth_logout
from django.contrib.auth import login
from authentication.forms import SignInForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect, get_object_or_404,reverse
from django.utils.decorators import method_decorator
from django.utils.encoding import force_text
from django.utils.http import is_safe_url
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect, ensure_csrf_cookie
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView

from .forms import SignUpForm,AccountSettingsForm,AccountInviteForm
from django.contrib.auth import get_user_model
from authentication.models import Email
from django.conf import settings
import django

Account = get_user_model()

# Create your views here.
lgr = logging.getLogger(__name__)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        primary_email = Email.objects.get(email=user.email)
        primary_email.is_verified = True
        primary_email.save()

        login(request, user,backend='authentication.backends.username_or_email.UsernameEmailBackend')
        return redirect(settings.INDEX_URL)
    else:
        return render(request, 'authentication/account_activation_invalid.html')


def account_activation_sent(request):
    return render(request, 'authentication/account_activation_sent.html')


class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    template_name = 'authentication/login.html'
    # template_name = 'partials/dash_menu.html'
    # template_name = 'web/dash_test.html'

    form_class = SignInForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(ensure_csrf_cookie)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        # request.session.set_test_cookie()
        # lgr.info("Test Cookie Set")
        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)

        return context


    def form_valid(self, form):
        auth_login(self.request, form.get_user())
        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        # if self.request.session.test_cookie_worked():
        #    lgr.info('test cookie worked')
        #    self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = reverse(settings.INDEX_URL)
        return redirect_to


class RegisterView(FormView):
    """
    Provides the ability to register user with a username and password
    """
    template_name = 'authentication/register.html'

    form_class = SignUpForm
    redirect_field_name = REDIRECT_FIELD_NAME

    @method_decorator(sensitive_post_parameters('password', 'password2'))
    @method_decorator(csrf_protect)
    @method_decorator(ensure_csrf_cookie)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        # Sets a test cookie to make sure the user has cookies enabled
        # request.session.set_test_cookie()
        # lgr.info("Test Cookie Set")
        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()


        # print('form save')

        if not user.is_superuser:
            # TODO from organizations.utils import create_organization
            #
            # organisation = create_organization(
            #     user,
            #     form.cleaned_data.get('organization','Rafikihost'),
            #     org_user_defaults={'is_admin': True}
            # )
            pass

        # auth_login(self.request, user)

        return super(RegisterView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        kwargs = {
            'url': redirect_to,
            'allowed_hosts':settings.ALLOWED_HOSTS
        }
        # Django 1.11+ allows us to require https, too.
        if django.VERSION >= (1, 11):
            kwargs['require_https'] = self.request.is_secure()
        # Django 2.1 drops support for the `host` kwarg.
        if django.VERSION <= (2, 0):
            kwargs['host'] = self.request.get_host()

        if not is_safe_url(**kwargs):
            redirect_to = reverse('authentication:account_activation_sent')
        return redirect_to


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    template_name = 'core/logout.html'
    pattern_name = settings.INDEX_URL

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class AccountSettingsView(FormView):
    """
    Provides the ability to register user with a username and password
    """
    template_name = 'authentication/profile.html'
    # success_url = '/account_activation_sent/'
    form_class = AccountSettingsForm
    redirect_field_name = REDIRECT_FIELD_NAME

    # todo finish
    # 'basic_information_form': basic_information_form,
    # 'login_information_form': login_information_form,

    # todo also finish
    # basic_information_form = AccountSettingsForm()
    # login_information_form = AccountSettingsForm()

    def dispatch(self, request, *args, **kwargs):
        return super(AccountSettingsView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        user = form.save()
        return super(AccountSettingsView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        kwargs = {
            'url': redirect_to,
            'allowed_hosts':settings.ALLOWED_HOSTS
        }
        # Django 1.11+ allows us to require https, too.
        if django.VERSION >= (1, 11):
            kwargs['require_https'] = self.request.is_secure()
        # Django 2.1 drops support for the `host` kwarg.
        if django.VERSION <= (2, 0):
            kwargs['host'] = self.request.get_host()

        if not is_safe_url(**kwargs):
            redirect_to = self.success_url
        return redirect_to

from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode
from django.utils.encoding import force_bytes
import random
import string


def random_string(stringLength=10):
    """Generate a random string of fixed length """
    letters = string.ascii_lowercase
    return ''.join(random.choice(letters) for i in range(stringLength))


def account_invite(request):
    if request.method == "POST":
        lgr.info(request.POST)
        form = AccountInviteForm(request.POST)
        if form.is_valid():
            password = random_string()

            user = Account()
            user.is_staff = False
            user.is_superuser = False
            user.is_active = False
            user.email = form.cleaned_data['email']
            user.set_password(password)
            user.save()

            if settings.PORT == 443 or settings.PORT == 80:
                PORT = ''
            else:
                PORT = (':{}'.format(settings.PORT) if settings.PORT else '')

            subject = 'Activate Your {} Account'.format(settings.PROJECT_NAME)
            message = render_to_string('authentication/account_invite_email.html', {
                'user': user,
                'protocol': settings.PROTOCOL,
                'domain': settings.HOST + PORT,
                'password': password,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode('utf-8'),
                'token': default_token_generator.make_token(user),
            })

            user.email_user(subject, message, from_email='noreply@'+settings.DOMAIN)

            return redirect('/')
        else:
            lgr.error('account invite form error')
            lgr.error(form.errors)

    else:
        form = AccountInviteForm()

    return render(request, 'authentication/account_invite.html',{
        'form':form
    })


def invite_accept(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = Account.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, Account.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        user.is_active = True
        user.save()

        login(request, user,backend='authentication.backends.username_or_email.UsernameEmailBackend')
        return redirect(settings.INDEX_URL)

    else:
        return render(request, 'authentication/account_activation_invalid.html')

authentication/templates/authentication/account_activation_email.html
{% autoescape off %}
Hi {{ user.get_full_name }},

Please click on the link below to confirm your registration:
{# TODO protocol #}
{{ protocol }}://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}

authentication/templates/authentication/account_activation_invalid.html
<p>The confirmation link was invalid, possibly because it has already been used.</p>

authentication/templates/authentication/account_activation_sent.html
{% extends 'authentication/layout.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-5 mx-auto">

            <div class="col-md-12 text-center">
                <img src="{% static 'images/logo.png' %}" alt="" style="width: 100%;"/>
            </div>

            <div class="text-center mt-2">
                <p class="text-center">
                    An activation link has been sent to you.<br>
                    Please confirm your email address to complete registration.
                </p>
            </div>
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/account_invite.html
{% extends 'authentication/layout.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-5 mx-auto">

            <div class="col-md-12 text-center">
                <img src="{% static 'images/logo.png' %}" alt="" style="width: 100%;"/>
            </div>

            <div class="text-center mt-2">
                <form action="{% url 'authentication:invite' %}" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <input type="submit" name="submit" class="btn btn-primary" value="Send">

                </form>
            </div>


        </div>
    </div>
{% endblock %}

authentication/templates/authentication/account_invite_email.html
{% autoescape off %}

Login credentials <br>
Your Email <br>
Password <strong>{{ password }}</strong> <br>
Please click on the link below to activate your account and complete registration:
{{ protocol }}://{{ domain }}{% url 'authentication:invite-accept' uidb64=uid token=token %}
{% endautoescape %}

authentication/templates/authentication/layout.html
{% extends 'application.html' %}

{% block app %}
    <div class="login">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </div>
{% endblock %}

authentication/templates/authentication/login.html
{% extends 'authentication/layout.html' %}
{% load web_filters %}
{% load static %}

{% block content %}


    <div class="row">
        <div class="col-md-5 mx-auto">

            <div class="col-md-12 text-center">
                <img src="{% static 'images/logo.png' %}" alt="" style="width: 100%;"/>
            </div>

            <form action="" method="post" name="login">
                {% csrf_token %}
                {% if form.non_field_errors %}
                    {% for non_field_error in form.non_field_errors %}
                        <p>{{ non_field_error }}</p>
                    {% endfor %}
                {% endif %}

                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p style="color: red">Error {{ error }}</p>
                        {% endfor %}
                    {% endif %}

                    {% if field.name == 'username' %}


                        <div class="form-group has-search">
                            <label for="{{ field.id_for_label }}">Email address or Username</label>
                            <span class="fa fa-user form-control-feedback"></span>
                            <input type="text" name="username" class="form-control" id="{{ field.id_for_label }}"
                                   placeholder="user@domain.com">
                        </div>


                    {% elif field.name == 'password' %}




                        <div class="form-group has-search">
                            <label for="{{ field.id_for_label }}">Password</label>
                            <span class="fa fa-lock form-control-feedback"></span>
                            <input type="password" id="{{ field.id_for_label }}" name="password" class="form-control"
                                   placeholder="********">
                            <div class="text-right">
                                <small><a href="{% url 'authentication:password_reset' %}">Forgot password?</a></small>
                            </div>
                        </div>



                    {% else %}


                        <div class="form-group">
                            {{ field|addclass:'form-control' }}

                        </div>

                    {% endif %}
                {% endfor %}



                <div class="form-group text-center ">
                    <button type="submit" class=" btn btn-block mybtn btn-login tx-tfm">Login</button>
                </div>

                <div class="form-group">
                    <p class="text-center singup-text">Don't have account? Sign up for free trial</p>
                </div>

                <div class="form-group text-center ">
                    <a href="{% url 'authentication:signup' %}" class=" btn btn-block mybtn btn-signup tx-tfm">Sign Up</a>
                </div>
            </form>

        </div>
    </div>

{% endblock %}

authentication/templates/authentication/profile.html
{% extends 'layout.html' %}

{% load staticfiles %}

{% block content %}

    <div class="profile">

        <form action="{% url 'authentication:settings' %}" method="post">
            <div class="row">

                <div class="col-md-12 ">
                    <div class="circle">
                        <!-- User Profile Image -->
                        <img class="profile-pic" src="{% static 'images/dummy-profile.png' %}">

                        <!-- Default Image -->
                        <!--                                 <i class="fa fa-user fa-5x"></i> -->
                    </div>
                    <div class="p-image">
                        <i class="fa fa-camera upload-button"></i>
                        <input class="file-upload" type="file" accept="image/*"/>
                    </div>

                </div>
            </div>

            <div class="row" style="margin-top: 3%;">
                <div class="col-md-5">
                    <h4>Basic Information</h4>

                    <div class="form-group">
                        <label for="exampleInputEmail1">First Name</label>
                        <input type="text" name="first_name" class="form-control" value="{{ request.user.first_name }}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Last Name</label>
                        <input type="text" name="first_name" class="form-control" value="{{ request.user.last_name }}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Company</label>
                        <input type="text" name="first_name"
                               class="form-control"
                               value="{% if request.user.company %}{{ request.user.company }}{% endif %}">
                    </div>
                </div>
                <div class="col-md-2"></div>

            </div>
            <div class="row" style="margin-top: 3%;">
                <div class="col-md-5">
                    <h4>Login Information</h4>

                    <div class="form-group">
                        <label for="exampleInputEmail1">Email</label>
                        <input type="email" name="first_name" class="form-control" value="{{ request.user.email }}">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Password</label>
                        <input type="password" name="first_name" class="form-control">
                        <a href="#" class="change-pass">Change Password?</a>
                    </div>
                </div>
                <div class="col-md-2"></div>

            </div>
            <div class="row" style="">
                <div class="col-md-12">
                    <div class="form-group">
                        <input type="submit" name="submit" class="btn mybtn btn-submit tx-tfm" value="Submit">
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

authentication/templates/authentication/register.html
{% extends 'authentication/layout.html' %}
{% load web_filters %}
{% load static %}

{% block content %}


    <div class="row">
        <div class="col-md-5 mx-auto">

            <div class="col-md-12 text-center">
                <img src="{% static 'images/logo.png' %}" alt="" style="width: 100%;"/>
            </div>

            <form action="{% url 'authentication:signup' %}" method="post" name="login">
                {% csrf_token %}
                {% if form.errors %}
                    <p>Please Correct the Errors Below</p>
                {% endif %}

                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <p style="color: red">Error {{ error }}</p>
                        {% endfor %}
                    {% endif %}

                    {% if field.name == 'email' %}


                        <div class="form-group has-search">
                            <label for="{{ field.id_for_label }}">Email address</label>
                            <span class="fa fa-user form-control-feedback"></span>
                            <input type="email" name="email" class="form-control" id="{{ field.id_for_label }}"
                                   placeholder="user@domain.com">
                        </div>


{#                    {% elif field.name == 'username' %}#}


                    {% elif field.name == 'password1' %}

                        <div class="form-group has-search">
                            <label for="{{ field.id_for_label }}">Password</label>
                            <span class="fa fa-lock form-control-feedback"></span>
                            <input type="password" name="password1" class="form-control" id="{{ field.id_for_label }}"
                                   placeholder="********">

                            <div class="text-left">
                                <small>{{ field.help_text|safe }}</small>
                            </div>

                        </div>



                    {% elif field.name == 'password2' %}

                        <div class="form-group has-search">
                            <label for="{{ field.id_for_label }}">Password Confirmation</label>
                            <span class="fa fa-lock form-control-feedback"></span>
                            <input type="password" name="password2" class="form-control" id="{{ field.id_for_label }}"
                                   placeholder="********">

                        </div>



                    {% else %}


                        <div class="form-group">
                            <label for="{{ field.id_for_label }}"
                                   {% if field.field.required %}required{% endif %}>{{ field.label }}</label>

                            {{ field|addclass:'form-control' }}

                        </div>

                    {% endif %}



                {% endfor %}



                <div class="form-group text-center ">
                    <button type="submit" class=" btn btn-block mybtn btn-login tx-tfm">Sign Up</button>
                </div>

                <div class="form-group">
                    <p class="text-center singup-text">Have an account? Sign In Instead</p>
                </div>

                <div class="form-group text-center ">
                    <a href="{% url 'authentication:login' %}" class=" btn btn-block mybtn btn-signup tx-tfm">Sign
                        In</a>
                </div>
            </form>

        </div>
    </div>

{% endblock %}