authentication/urls.py
from django.conf.urls import url
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

from .views import account_activation_sent,account_invite,invite_accept
from authentication import views as core

app_name = 'authentication'

urlpatterns = [

    url(r'^login/$', core.LoginView.as_view(), name='login'),
    url(r'^signup/$', core.RegisterView.as_view(), name='signup'),
    url(r'^invite/$', account_invite, name='invite'),
    url(r'^invite/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/accept$',
        invite_accept,
        name='invite-accept'),
    url(r'^logout/$', core.LogoutView.as_view(), name='logout'),
    url(r'^profile/$', core.AccountSettingsView.as_view(), name='settings'),

    url(r'^password_reset/$',
        auth_views.PasswordResetView.as_view(**{
            'template_name': 'authentication/registration/password_reset_form.html',
            'from_email': 'salesleadgen@mohit-development.website',
            'email_template_name': 'authentication/registration/password_reset_email.html',
            'subject_template_name': 'authentication/registration/password_reset_subject.txt',
            'success_url':reverse_lazy('authentication:password_reset_done')
        }),
        name='password_reset'
        ),
    url(r'^password_reset/done/$',
        auth_views.PasswordResetDoneView.as_view(
            **{'template_name': 'authentication/registration/password_reset_done.html'}),
        name='password_reset_done'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core.activate, name='activate'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(**{
            'success_url': reverse_lazy('authentication:password_reset_complete'),
            'template_name': 'authentication/registration/password_reset_confirm.html'
        }),
        name='password_reset_confirm'
        ),
    url(r'^reset/done/$',
        auth_views.PasswordResetCompleteView.as_view(**{
            'template_name': 'authentication/registration/password_reset_complete.html'
        }),
        name='password_reset_complete'),
    url(r'^account_activation_sent/$', account_activation_sent, name='account_activation_sent'),

]

core/urls.py
from django.conf.urls import url,include
from core.views import (
    dashboard,

)

app_name = 'core'

urlpatterns = [

    url(r'^$', dashboard, name='dashboard'),

    # url(r'^ta', core_ta, name='ta'),

    # url(r'^sample_model/', include(([
    #     url(r'^create$', search_create,name='create'),
    #
    #     url(r'^(?P<sample_model_pk>\d+)/', include(([
    #         url(r'^$', search_summary, name='summary'),
    #         url(r'^track_node$', search_track_node, name='track_node'),
    #
    #     ],'search'))),
    # ],'searches'))),
]

project/urls.py
from django.contrib import admin
from django.conf.urls import include, url

from django.urls import path
from django.conf import settings

urlpatterns = [
    path('', include('authentication.urls')),
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    # django debug toolbar
    import debug_toolbar

    urlpatterns = [
                      path(r'__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

templates/application.html
<!DOCTYPE html>
<html lang="en">
<head>

    <title>Application :: {% block title %}TODO{% endblock %}</title>
    <meta charset="UTF-8">


    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Django Starter">
    <meta name="author" content="danleyb2 <me.danleyb2.online>">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load staticfiles %}
	<link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
          integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css"/>

</head>

<body>

    {% block app %}
    {% endblock %}
    {% block layout_scripts %}{% endblock %}
    {% block scripts %}{% endblock %}


</body>

</html>

templates/layout.html
{% extends 'application.html' %}

{% load staticfiles %}

{% block app %}



    <div class="header fixed-top">
        <div class="container-fluid">
            <nav class="navbar navbar-expand-lg navbar-light ">
                <a class="navbar-brand" href="{% url 'core:dashboard' %}">
                    <img src="{% static 'images/logo.png' %}" alt="" style="width: 70%;">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#">Action</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Another</a>
                        </li>

                        <li class="nav-item dropdown dropdown-slide dropdown-hover">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle nav-link dropdown-user-link">
                                    <span class="avatar">
                                        <img src="{% static 'images/user.png' %}" alt="avatar"><i></i></span>
                                <h6 class="user-name"> {{ request.user.username }}</h6>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="{% url 'authentication:settings' %}">Profile</a>

                                <a class="dropdown-item" href="{% url 'authentication:logout' %}">Log Out</a>

                                {% if request.user.is_superuser %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                                {% endif %}
                                <!-- <a class="dropdown-item" href="#">Something else here</a>-->
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>


    <div class="main-body">
        <div class="container">

            {% if not request.user.salesnavigatoraccount.logged_in %}
            <div class="alert alert-danger" role="alert">
              Please First Do 123 <a class="alert-link" href="{% url 'core:dashboard' %}">Here</a>
            </div>
            {% endif %}

            {% block content %}{% endblock %}
        </div>
    </div>

    <div class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p>2019 - django-starter</p>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block layout_scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}" type="text/javascript"></script>

{% endblock %}